
[hud]
	#Whether to show the feathers in the UI.
	show_hud = true
	#Whether to show the tutorial on joining a new world.
	tutorial = true
	#Whether to show armor weight tooltips. If Quark is installed, please restart the game after disabling or enabling 'Quark Settings -> Client -> Visual Stat Display'.
	tooltips = true

[controls]
	#Enable to make dodging left, right or backwards require a double tap, and forwards require a tap of the dodge button.
	double_tap = true
	#How many system ticks you have between double tapping (these are faster than Minecraft ticks).
	#Range: > 1
	double_tap_ticks = 175

