
#General mod settings
[general]
	useGroundDodge = true
	useLedgeClimb = true
	#Range: > 0
	doubleTapDodgeMaxTimeInMilliseconds = 300
	#Range: 0.0 ~ 1.0
	knockbackResistAmount = 0.3
	dontGroundDodgeIfSneaking = true
	#Range: 0.0 ~ 1.0
	groundDodgeForceHorizontal = 1.0
	#Range: 0.0 ~ 0.5
	groundDodgeForceVertical = 0.4

